spring:
  application:
    name: 'Let Me Ask'

  profiles:
    active: ${SPRING_PROFILE:dev}

  cors:
    origins: ${ALLOWED_ORIGINS:'*'}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

gemini:
  api-key: ${GOOGLE_API_KEY}
